Fix for URL path handling on Windows. (Fixes #266)
cloudfoundry/credhub pull request #267
Opened 2022-03-14 22:02 UTC by thomas-worm-datev

This pull request fixes URL path handling on Windows.

2022-03-14 22:46 UTC, thomas-worm-datev commented
This pull request fixes the [issue #266](https://github.com/cloudfoundry/credhub/issues/266).

2022-03-31 20:32 UTC, bruce-ricard requested changes
Hi @thomas-worm-datev , thank you for your PR.

Could you please add a test to your change please, to explain and describe what your change is about?

Thanks.

2022-05-04 10:58 UTC, strehle commented on components/auth/src/main/kotlin/org/cloudfoundry/credhub/config/OAuthProperties.kt
> +    private fun concatPath(p1: String, p2: String): String {
hi @bruce-ricard  I checked the usage and it is for credhub internal resolution of pathes to UAA so with 
https://github.com/cloudfoundry/credhub/pull/325/files it simply does same / similar this we have in UAA already in order to resolve pathes to OIDC endpoints

2022-05-23 23:01 UTC, hsinn0 commented
https://github.com/cloudfoundry/credhub/issues/266 already fixed and closed with another PR

2022-05-23 23:01 UTC, closed without merging