Pin notAfter dates for certificates to max out at signing CA notAfter date
cloudfoundry/credhub pull request #378
Opened 2022-09-12 03:56 UTC by ae-govau

This prevents one from issuing a certificate that appears to be valid, but in reality typically won't validate as being so.

Partially fixes #377

2022-09-12 05:23 UTC, ae-govau commented
Accepting the CLA from our env is challenging (we've clicked through CLAs before for I think other parts of Cloudfoundry, but that particular one seems to be more complex for us to navigate for some reason). It's a trivial PR, feel free to pick up the few lines added into a new one if necessary.

Else, and if you'd like this change, let me know and I'll try harder to get the CLA organised.

2022-11-07 23:44 UTC, swalchemist requested changes
Thanks, this looks useful, just needs to be tightened up. Also, first can you look into the EasyCLA issue and get that done? Let us know if you need some help with it.

2022-11-07 23:44 UTC, swalchemist commented on components/credentials/src/main/java/org/cloudfoundry/credhub/generators/SignedCertificateGenerator.java
> +    Data nva = Date.from(now.plus(Duration.ofDays(params.getDuration())));
This doesn't compile - should be "Date". Please run "gradlew test" after fixing.

2022-11-07 23:44 UTC, swalchemist commented on components/credentials/src/main/java/org/cloudfoundry/credhub/generators/SignedCertificateGenerator.java
> +    Date nvb = Date.from(now);
I suggest more descriptive names like notBefore and notAfter.

2022-11-07 23:44 UTC, swalchemist commented on components/credentials/src/main/java/org/cloudfoundry/credhub/generators/SignedCertificateGenerator.java
> +    if (issuerCertificate != null) {
Could you add unit test coverage for this new logic? I'm assuming we didn't already have good assertions for it, even though the tests hit this code.

2022-11-07 23:44 UTC, swalchemist commented on components/credentials/src/main/java/org/cloudfoundry/credhub/generators/SignedCertificateGenerator.java
> +      if (nvb.isBefore(issuerCertificate.getNotBefore())) {
There isn't an `isBefore` method on Date, but you can use `before`.

2022-11-07 23:44 UTC, swalchemist commented on components/credentials/src/main/java/org/cloudfoundry/credhub/generators/SignedCertificateGenerator.java
> +      if (nva.isAfter(issuerCertificate.getNotAfter())) {
`isAfter` should be `after'.

2024-03-18 20:52 UTC, Tallicia commented
@ae-govau Do you plan to complete the CLA in the near future?

2024-09-09 18:38 UTC, hsinn0 commented
Closing non active old PRs

2024-09-09 18:38 UTC, closed without merging