doc: how to clean up orphaned encrypted_value records
cloudfoundry/credhub pull request #712
Opened 2024-03-20 20:07 UTC by hsinn0

[#182121168]

Documenting how to cleanup orphaned records as noted in https://github.com/cloudfoundry/credhub/issues/231. Part of SQL scripts here were taken from the issue.
Added a section about the orphaned data cleanup steps in `README.md`.

2024-03-20 21:00 UTC, peterhaochen47 commented
Could we maybe add this instruction in the ["/docs" directory](https://github.com/cloudfoundry/credhub/tree/830bb16eade21e98cc74b6916419f98fa279a719/docs), and maybe put a link to it in the main README?

I feel that putting a lengthy instruction on a specific issue in the main README might crowd out the high-level overview info that people are typically looking for in a main repo README.

2024-03-20 21:25 UTC, Tallicia commented
I agree this should be links from the readme, 1 for each database separately.

2024-03-20 21:42 UTC, hsinn0 commented
> Could we maybe add this instruction in the ["/docs" directory](https://github.com/cloudfoundry/credhub/tree/830bb16eade21e98cc74b6916419f98fa279a719/docs), and maybe put a link to it in the main README?

Moved to separate doc.

2024-03-20 21:43 UTC, hsinn0 commented
> I agree this should be links from the readme, 1 for each database separately.

Moved but kept them in a single doc.

2024-03-20 23:56 UTC, emalm requested changes
Looks good to me! I just had a few minor adjustments to the surrounding explanatory text.

2024-03-20 23:56 UTC, emalm commented on docs/orphaned-encryption-value-cleanup.md
> +described below.
```suggestion
CredHub version 2.12.66 and earlier had a bug where `encrypted_value`
records were not deleted when the associated credentials were deleted.
(See https://github.com/cloudfoundry/credhub/issues/231.)

To clean up the orphaned `encrypted_value` records that accumulated
on these older CredHub versions, run the SQL script below for your database type.
```

2024-03-20 23:56 UTC, emalm commented on docs/orphaned-encryption-value-cleanup.md
> +### For postgresql database
```suggestion
### For PostgreSQL
```

2024-03-20 23:56 UTC, emalm commented on docs/orphaned-encryption-value-cleanup.md
> +-- Step 2: Optoinal. Get the number of encrypted_value records that are not in any of those 3 tables
```suggestion
-- Step 2: Optional. Get the number of encrypted_value records that are not in any of those 3 tables
```

2024-03-20 23:56 UTC, emalm commented on docs/orphaned-encryption-value-cleanup.md
> +next step for example.
```suggestion
Note that adding indexes and running the queries may take a very long time if you
have a large CredHub database. You may want to run each query separately. In
particular, you may want to count the number of orphaned records first to
determine whether cleaning them up will reduce the size of your CredHub
database significantly.
```

2024-03-20 23:56 UTC, emalm commented on docs/orphaned-encryption-value-cleanup.md
> +### For mysql database
```suggestion
### For MySQL or MySQL-compatible databases, such as MariaDB
```

2024-03-20 23:56 UTC, emalm commented on docs/orphaned-encryption-value-cleanup.md
> +-- Step 1: Optoinal. Get the number of encrypted_value records that are not in any of those 3 tables
```suggestion
-- Step 1: Optional. Get the number of encrypted_value records that are not in any of those 3 tables
```

2024-03-20 23:56 UTC, emalm commented on docs/orphaned-encryption-value-cleanup.md
> +to next step.
```suggestion
For MySQL database, the necessary indexes are already there, so you do not have
to create them. The queries still may take a long time to run if you have a large
database. You may want to get the number of orphaned records before proceeding
to the deletion step.
```

2024-03-20 23:56 UTC, emalm commented on README.md
> +[Cleaning up orphaned encrypted_value records](docs/orphaned-encryption-value-cleanup.md).
```suggestion
### Cleaning up orphaned encrypted_value records
To clean up orphaned `encrypted_value` records from CredHub version 2.12.66 and
earlier (https://github.com/cloudfoundry/credhub/issues/231), follow the steps decribed in
[Cleaning up orphaned encrypted_value records](docs/orphaned-encryption-value-cleanup.md).
```

2024-03-21 16:09 UTC, emalm approved these changes

2024-03-21 16:54 UTC, merged