doc: The need to stay with protobuf 3.25.x
cloudfoundry/credhub pull request #718
Opened 2024-04-03 17:46 UTC by hsinn0

2024-04-03 18:27 UTC, Tallicia approved these changes
This is good. Monthly checks for updates should keep this updated if there are any more 3.xx updates, yes? Or is 3.xx no longer supported?

2024-04-03 18:28 UTC, peterhaochen47 requested changes
Could we maybe use a variable, similar to `commonsCodecVersion`, that is declared in the [main build.gradle](https://github.com/cloudfoundry/credhub/blob/3d20de779bc62f11a5a073d484cb9272eff07b9c/build.gradle) where the comment can also go. This way, all the intentional version pinning and their justifications/criterion for unpinning are all in the same place.

2024-04-03 18:44 UTC, hsinn0 commented
> This is good. Monthly checks for updates should keep this updated if there are any more 3.xx updates, yes? Or is 3.xx no longer supported?

3.xx is not end of support. We could configure dependabot to ignore major version bumps only. However for this, I'd like to see all version bump PRs because its relationship with grpc version, as explained in the comment.

2024-04-04 19:48 UTC, peterhaochen47 approved these changes

2024-04-04 20:39 UTC, merged